name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run Pester tests
      run: |
        $config = New-PesterConfiguration
        $config.Run.Path = 'tests'
        $config.TestResult.Enabled = $true
        $config.CodeCoverage.Enabled = $true
        Invoke-Pester -Configuration $config
      shell: pwsh
      continue-on-error: true

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./testResults.xml
  publish:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Publish to PowerShell Gallery
      if: success()
      env:
        PSGalleryApiKey: ${{ secrets.PSGALLERY_API_KEY }}
      run: |
        .\Build.ps1 -Package -Analyze -patchVersion "${{ github.run_number }}-${{ github.run_attempt }}" -NuGetApiKey $env:PSGalleryApiKey